apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: myapp_container
          image: devops:latest
