apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappcontainer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myappcontainer
  template:
    metadata:
      labels:
        app: myappcontainer
    spec:
      containers:
        - name: myappcontainer
          image: devops:latest
---
apiVersion: v1
kind: Service
metadata:
  name: myappcontainer
  namespace: default
spec:
  ports:
    - name: http
      port: 4200
  type: LoadBalancer    
  selector:
    apps: myappcontainer
