---
# tasks file for docker-registry
- name: log into docker hub registy
  docker_login:
    email: "nour.mallek@esprit.tn"
    username: "nourmallek1"
    password: "dckr_pat_fzZC4kGqY6E5sxmlr0uAgt_zlPM"
- name: Push the Docker image into the repo
  shell: docker push nourmallek1/devops:latest
