---
# tasks file for docker-registry
- name: log into docker hub registy
  docker_login:
    email: "nour.mallek@esprit.tn"
    username: "nourmallek1"
    password: "dckr_pat_fzZC4kGqY6E5sxmlr0uAgt_zlPM"
- name: Tag and push to docker hub
  docker_image:
    name: devops
    repository: nourmallek1/devops
    push: yes
    source: local
